In [22]:
import pandas as pd
from Bio.Seq import Seq
from Bio import Entrez
import os
from typing import List, Dict

In [23]:
os.chdir('C:\\Users\\jcham\spanins')
os.getcwd()

'C:\\Users\\jcham\\spanins'

### Showing table dimensions

In [24]:
data = pd.read_csv('category_I_sequence_diff.csv')
data.shape

(122, 13)

### Showing NaN rows
* 10 of the NaN rows do not have any ncbi_sequence data (probably weren't called at all by the submitter, but were called by rohit)
* The other 10 do have ncbi_sequence data but are missing something else
* Rows 6, 8, 9, 15, 20, 28, and 32 are missing only the property_feature data. These rows should be manageable with the planned script
* Rows 45, 79 and 99 have sequence data but no cds or strand. Probably need to be dealt with manually. 
* All others remaining (2, 5, 25, 40, 41, 42, 74, 81, 114, 118) were not called by the submitter.

In [25]:
data[data.isna().any(axis=1)]

,host,host_taxid,phage_acc,protein_acc,protein_gi,cds,strand,function,spanin_type,property_feature,sequence,ncbi_sequence,same
2,Enterobacteria,547,AP011113,NaN,26042140,NaN,NaN,ISPANIN,sep,TMD:5..24,MHVSNFTAGLLLLVIAFGGTSIILKNKVERLETSVVEITKTANENA...,NaN,NaN
5,Escherichia,561,EU078592,NaN,40093751,NaN,NaN,ISPANIN,emb,TMD:4..26,MSRVTAIISALVICIIVCLSWAVNHYRDNAITYKAQRDKNARELKL...,NaN,NaN
6,Pseudomonas,286,NC_007805.1,YP_001293406.1,148912827,37910..38360,POSITIVE,ISPANIN,emb,NaN,MRWVPWLVVALVAALVFWRLDHVTAQRNDLQAAVEQSAETITAMAQ...,MVALVAALVFWRLDHVTAQRNDLQAAVEQSAETITAMAQQAQRDTQ...,N
8,Salmonella,590,NC_010392.1,YP_001700615.1,169257238,30405..30858,NEGATIVE,ISPANIN,emb,NaN,MMFNWKTMFVGLLLVSLIVAGRLANHYRNNAITYKYQRDTATHNLK...,MFVGLLLVSLIVAGRLANHYRNNAITYKYQRDTATHNLKLANETIT...,N
9,Salmonella,590,NC_010393.1,YP_001700673.1,169257297,17493..17973,POSITIVE,ISPANIN,emb,NaN,MMFNWKTMFVGLLLVSLIVAGRLANHYRNNAITYKEQRDTVTHRLT...,MFVGLLLVSLIVAGRLANHYRNNAITYKEQRDTVTHRLTLANATIT...,N
15,Escherichia,561,NC_024379.1,YP_009044294.1,658607293,36334..36736,POSITIVE,ISPANIN,emb,NaN,MLEFLKRAAPWLLAAVMFAGGYHTANNKWEAKVNAEYTSNLKASED...,MFAGGYHTANNKWEAKVNAEYTSNLKASEDTRLAVQAEVNKVSKRF...,N
20,Burkholderia,32008,NC_009234.1,YP_001111073.1,134288770,32853..33276,NEGATIVE,ISPANIN,ovl,NaN,MNLSRLMPWLALFALIALAASCQHGRALRAQLERATDDARRANRDA...,MPWLALFALIALAASCQHGRALRAQLERATDDARRANRDAQASAAV...,N
25,Yersinia,629,HE956707,NaN,398313030,NaN,NaN,ISPANIN,ovl,TMD:10..27,MLTIPNKYKWAVMALLAAVSIGSLTLANHYRDSALTSQKALQEVTD...,NaN,NaN
28,Yersinia,629,AM076770,CAJ28448.1,164414553,18144..18336,POSITIVE,ISPANIN,ovl,NaN,MLGKLKIAVMLMIAAVLAWKAGSWNGARVERSVQIAECNNRIEKLA...,MQIAECNNRIEKLAAELEAEKAKKKVEVTKSASKTKQSVLVATDSD...,N
32,Stenotrophomonas,40323,NC_023588.1,YP_009008371.1,589892004,9447..9939,POSITIVE,ISPANIN,emb,NaN,MLYRALALAALVLATAGLFSYQQGRISRATTALDKANLDLAKARSE...,MLATAGLFSYQQGRISRATTALDKANLDLAKARSENAALTSSLKLA...,N
40,Escherichia coli O157:H7,561,KM092515,NaN,26631539,NaN,NaN,ISPANIN,ovl,TMD:10..27,MTFKEFCQATFIIVFLVGAGVWGGYSYRDYQVAEAELSNEKLISVA...,NaN,NaN
41,Enterobacteria,547,NC_011045.1,NaN,93201455,NaN,NaN,OSPANIN,emb,LIPO:29..32,MKYRLSIKKTLPRWKGALIGLFLICVATISGCVSESKLPEPPMVSV...,NaN,NaN
42,Enterobacteria,547,AP011113,NaN,26042139,NaN,NaN,OSPANIN,sep,LIPO:14..17,MIKLSAVILSIGLLVGCSTKPLEVKKETVHPNWPVQIKSYDEAKLS...,NaN,NaN
45,Campylobacter,194,FN667789.1,CBJ94317.1,294338279,NaN,NaN,OSPANIN,sep,LIPO:15..18,MKFKKFLLALIPFIFVGCSAVRTEFIYPKIPDVKEPPMTQDYNLTV...,MKFKKFLLALIPFIFVGCSAVRTEFIYPKIPDVKEPPMTQDYNLTV...,N
74,vibrio,662,NC_005083.2,NaN,2546051,NaN,NaN,OSPANIN,sep,LIPO:14..17,MVNKIIAIALCLTLVGCIGTPKEPVPEPPKNEIVHPNIPTPPPNPG...,NaN,NaN
79,Edwardsiella,635,NC_021342.1,NaN,509141582,NaN,NaN,OSPANIN,ovl,LIPO:16..19,MSIVSKLLLCGIVCAIAGCSNSTTRHSDCPTVSSDLLVPPRKLEST...,MLVPPRKLESTHNDPERAAWVIPWNAEALLADRSRLERWQAWYNAT...,N
81,Bdellovibrio,662,NC_015721.1,NaN,33882695,NaN,NaN,OSPANIN,ovl,LIPO:25..28,MQKNIRMPRLGPIKFALLLILSIGIISCAGVPKFPKDIKVWETAYL...,NaN,NaN
99,Enterobacteria,547,NC_012223,NaN,225220121,NaN,NaN,OSPANIN,ovl,LIPO:14..17,MLRALTALIVVLTLSACGSSSVPLMPLTESALRLPCKFDNPSADPD...,MIDVKNMECGAKLRAQVLELQQIIKGP,N
114,Escherichia coli O157:H7,561,KM092515,NaN,26631540,NaN,NaN,OSPANIN,ovl,LIPO:17..20,MKKLSQSFIMFVLLIIMSGCSTNKVSSTFKNSQVSESDKYTQEESR...,NaN,NaN
118,vibrio,662,NC_023863.2,NaN,657201235,NaN,NaN,USPANIN,USP,LIPO:14..17,MKIISTILLSLALLTGCSAMQMATGIASTLSGEQPSLSVDAQMGDR...,NaN,NaN

### Dropping NaN rows (20/122 rows dropped)

In [26]:
data = data.dropna(axis=0)
data.shape

(102, 13)

In [27]:
data.head(3)

,host,host_taxid,phage_acc,protein_acc,protein_gi,cds,strand,function,spanin_type,property_feature,sequence,ncbi_sequence,same
0,Aeromonas,642,NC_020879.1,YP_007677913.1,472438133,126555..126789,NEGATIVE,ISPANIN,sep,TMD:7..29,MLLTLSSLLSWLKSNALCIIIMVLMAIMMKNQHDEISTLKTSLESM...,MKNQHDEISTLKTSLESMKSFQTKSYENAKPVTEALLKSPKATKQM...,N
1,Aeromonas,642,NC_019543.1,YP_007010874.1,423262275,124571..124826,NEGATIVE,ISPANIN,sep,TMD:7..29,MLLTLSSLLSWLKSNALYIIIMVLMAIMMKNQHDEISTLKNSLESM...,MVLMAIMMKNQHDEISTLKNSLESMKSFQTKSYENAKPVTEALLKS...,N
3,Enterobacteria,547,NC_024142.1,YP_009031980.1,640884671,12841..13066,POSITIVE,ISPANIN,emb,TMD:10..27,MKMLISKGWPYLLVVVLGATIYFWGNSNGQSTVQKKWDDQKVEDQK...,MQQSERRASVYKRQAEAGTFECRSLASHAARLDNSLEEGRRLVEEL...,N

In [28]:
data2 = data[['cds', 'sequence', 'ncbi_sequence']].copy()
data2.head(3)

,cds,sequence,ncbi_sequence
0,126555..126789,MLLTLSSLLSWLKSNALCIIIMVLMAIMMKNQHDEISTLKTSLESM...,MKNQHDEISTLKTSLESMKSFQTKSYENAKPVTEALLKSPKATKQM...
1,124571..124826,MLLTLSSLLSWLKSNALYIIIMVLMAIMMKNQHDEISTLKNSLESM...,MVLMAIMMKNQHDEISTLKNSLESMKSFQTKSYENAKPVTEALLKS...
3,12841..13066,MKMLISKGWPYLLVVVLGATIYFWGNSNGQSTVQKKWDDQKVEDQK...,MQQSERRASVYKRQAEAGTFECRSLASHAARLDNSLEEGRRLVEEL...

* Need to parse sequence and ncbi_sequence against one another, checking if one is a subset of another.
* If so, determine the difference in lengths between the larger one and the smaller
* Multiply this difference by three. The starting CDS should be approximately that many bases before or after the NCBI CDS (or +1 the NCBI CDS due to messed up indexing?)

### Creating list of the protein sequences (rohit's spanin calls vs NCBI's)

In [29]:
rohit_calls: List[str] = list(data['sequence'])
ncbi_calls: List[str] = list(data['ncbi_sequence'])
[v for v in ncbi_calls][:2]

['MKNQHDEISTLKTSLESMKSFQTKSYENAKPVTEALLKSPKATKQMEKIAEKKPQLLEKRMNMGFQKLADQLQESTK',
 'MVLMAIMMKNQHDEISTLKNSLESMKSFQTKSYENAKPVTEALLKSPKATKQMEKIAEKKPQLLEKRMNMGFQKLADQLQESTK']

### Iterates over ncbi/rohit calls, checking if each sequence is a subset of the other, or if they are identical

In [40]:
ncbi_subset_of_rohit: List[bool] = [v in rohit_calls[i] for i, v in enumerate(ncbi_calls)]
rohit_subset_of_ncbi: List[bool] = [v in ncbi_calls[i] for i, v in enumerate(rohit_calls)]
identical: List[bool] = [v == ncbi_calls[i] for i, v in enumerate(rohit_calls)]
print(' ncbi seqs contained in rohit seqs:', sum(ncbi_subset_of_rohit), 
      '\n', 'rohit seqs contained in ncbi seqs:', sum(rohit_subset_of_ncbi), 
      '\n', 'sequence calls are the same:', sum(identical),
      '\n', 'total seqs in dataset:', data.shape[0])

 ncbi seqs contained in rohit seqs: 53
 rohit seqs contained in ncbi seqs: 10
 sequence calls are the same: 0
 total seqs in dataset: 102

### Adding these subset seqs to a df

In [47]:
data2['ncbi_subset_of_rohit'] = ncbi_subset_of_rohit
data2['rohit_subset_of_ncbi'] = rohit_subset_of_ncbi
print(data2['sequence'].loc[4], data2['ncbi_sequence'].loc[4])

MQMFNFLFSFIKSNIIYILLGSLLAFTAYRYISLEKSNAILIENEKQLTQNIKNSKKELEALKNYNNLTEVFREKEVKYKEVLNNIKNIETKIQKLKLMRKDENETQYIIVNF MQMFNFLFSFIKSNIIYILLGSLLAFTAYRYISLEKSNAILIENEKQLTQNIKNSKKELEALKNYNNLTIEVFREKEVKYKEVLNNIKNIETKIQKLKLMRKDENETQYIIVNF

### Finds the difference between two strings

* Need to run this on all strings which are not subsets of one another

* *This ideally needs to give the index where the difference occurs as well*

In [52]:
import difflib
row4_rohit = data2['sequence'].loc[4]
row4_ncbi = data2['ncbi_sequence'].loc[4]

case_a = 'MQMFNFLFSFIKSNIIYILLGSLLAFTAYRYISLEKSNAILIENEKQLTQNIKNSKKELEALKNYNNLTEVFREKEVKYKEVLNNIKNIETKIQKLKLMRKDENETQYIIVNF'
case_b = 'MQMFNFLFSFIKSNIIYILLGSLLAFTAYRYISLEKSNAILIENEKQLTQNIKNSKKELEALKNYNNLTIEVFREKEVKYKEVLNNIKNIETKIQKLKLMRKDENETQYIIVNF'

output_list = [li for li in difflib.ndiff(case_a, case_b) if li[0] != ' ']
print(' rohit:', row4_rohit, '\n', 'ncbi: ', row4_ncbi, '\n difference:', output_list)

 rohit: MQMFNFLFSFIKSNIIYILLGSLLAFTAYRYISLEKSNAILIENEKQLTQNIKNSKKELEALKNYNNLTEVFREKEVKYKEVLNNIKNIETKIQKLKLMRKDENETQYIIVNF
 ncbi:  MQMFNFLFSFIKSNIIYILLGSLLAFTAYRYISLEKSNAILIENEKQLTQNIKNSKKELEALKNYNNLTIEVFREKEVKYKEVLNNIKNIETKIQKLKLMRKDENETQYIIVNF
 difference: ['+ I']

#### Find the difference in length between each subset pair
* To select each row, need a pandas series

In [32]:
#sor = subset_of_rohit
ncbi_protein_seqs_sor: List[str] = [v if for i, v in enumerate(rohit_calls)] 

ncbi_differences: List[int] = 
    # - data[data['ncbi_sequence'] == ncbi_subset_of_rohit]
ncbi_differences[:]

SyntaxError: invalid syntax (<ipython-input-32-b13e7c903c1c>, line 2)

In [ ]:
def check_if_subset(df: DataFrame) -> List[Bool]:
    import pandas as pd
    # loop through df at sequence and ncbi_sequence
    # append each to a separate list
    rohit_orfs = list(df['sequence'])
    ncbi_orfs = list(df['ncbi_sequence'])
    # import 
    
# could make a function that compares if a string is a subset of another string. if not, tries the reverse. If neither are true, outputs 'not subsets'
#

In [ ]:
# NOT WORKING as expected
# ncbi_sor = data['ncbi_sequence'].isin(data['sequence'])
# ncbi_sor

In [ ]:
data.query("'ncbi_sequence' in 'sequence'")